### ISSUE TITLE
Invalid YAML with `-y` option

### ISSUE THREAD

**Issue by justinlovinger** [alex-courtis/way-displays#107]
Calling `way-displays -y -g` provides invalid YAML because the `INFO` key is duplicated in `MESSAGES`. Some YAML parsers will fail to parse `way-displays -y -g`.

**Comment by alex-courtis** [comment]
I've only ever used `yq` and yaml-cpp to parse it; apologies for the duplicates.
 
It might be best to just remove messages from the YAML output; they are really only for the human output.

**Comment by JustinLovinger** [comment]
> I've only ever used `yq` and yaml-cpp to parse it; apologies for the duplicates.

No problem. I was able to work around the issue by converting the YAML to valid JSON using `yq`.

> It might be best to just remove messages from the YAML output; they are really only for the human output.

I agree. The `-y` output should be easily parsable, which the messages are not, and the messages contain redundant information.

**Comment by alex-courtis** [comment]
This is great, thank you. Tracking at #109

**Comment by alex-courtis** [comment]
Fixed on master.

@JustinLovinger I would be grateful if you could test:

```
git clone git@github.com:alex-courtis/way-displays.git
cd way-displays
git submodule update --init
make
sudo make install
```

When you are done you can
```
sudo make uninstall
```

**Comment by alex-courtis** [comment]
`MESSAGES` are now a sequence of maps by log level and only warnings/errors are present.

**Comment by alex-courtis** [comment]
Done: #123
