### ISSUE TITLE
option: set specific resolution

### ISSUE THREAD

**Issue by alex-courtis** [alex-courtis/way-displays#13]
"10-max-optimal-refresh" branch also works with a 165 Hz monitor!

I'm also thinking about fixing into a specified resolution for some cases like some monitor controllers(a generic one for various display panels) report max resolution over native panel resolution. I will try to code some.

_Originally posted by @raxetul in https://github.com/alex-courtis/way-displays/issues/10#issuecomment-1003688049_

**Comment by alex-courtis** [comment]
> report max resolution over native panel resolution

That is a problem. I'm not surprised, as monitors have inconsistent resolution reporting behaviour.

Can you please collect this monitor's reported information as per [comment](https://github.com/alex-courtis/way-displays/issues/10#issuecomment-982075444)?

I did try always setting to maximum resolution instead of preferred, however this failed on one of my monitors when connected over HDMI instead of DP. With more real world information we can come up with a solution.

**Comment by alex-courtis** [comment]
Closing this issue continuing in #19.

**Comment by raxetul** [comment]
Sorry to see late
