### ISSUE TITLE
Feature: recipe for using rofi as menu for way-displays 

### ISSUE THREAD

**Issue by jeadorf** [alex-courtis/way-displays#140]
![rofi](https://github.com/alex-courtis/way-displays/assets/2495626/7364d72c-8a50-4895-8e50-9e86a8aca81b)

> A beautiful TUI to manage displays. Would you care to share your setup / configuration? That would be the start of the Recipes wiki page.

_Originally posted by @alex-courtis in https://github.com/alex-courtis/way-displays/issues/121#issuecomment-1807269270_

**Comment by jeadorf** [comment]
I'm using rofi (https://github.com/davatorium/rofi, https://wiki.archlinux.org/title/rofi), together with a customized rust program driving the interactive menu, displayed by rofi. In order to make the recipes more self-contained and thus useful (minimal dependencies), I need to post some examples on how to use rofi and way-displays with the least amount of customization. But once you get the gist on how rofi works, should be fairly straight-forward to include shortcuts to way-displays like the ones in the screenshot.

**Comment by jeadorf** [comment]
The following example

![rofi-example](https://github.com/alex-courtis/way-displays/assets/2495626/4ba9ce76-d58a-4ce0-8170-ba136fe4a683)

allows user to switch between internal only, external only, or both displays.

```sh
#/bin/sh

# Configure names of external and internal displays
EXTERNAL="HDMI-A-1"
INTERNAL="eDP-1"

function show() {
  way-displays --delete DISABLED "$1" > /dev/null
}

function hide() {
  way-displays -s DISABLED "$1" > /dev/null
}

OPT_INTERNAL="Internal display"
OPT_EXTERNAL="External display"
OPT_BOTH="Both displays"

function menu() {
  echo "${OPT_INTERNAL}"
  echo "${OPT_EXTERNAL}"
  echo "${OPT_BOTH}"
}

OPTION=$( (menu)  | rofi -dmenu -p "Configure displays")

# Invoke way-displays. Only hide a display if showing the other display
# succeeded. This reduces the chances to end up with both displays turned off,
# which is typically rather inconvenient.
if [ "${OPTION}" == "${OPT_INTERNAL}" ]
then
  show "${INTERNAL}" && hide "${EXTERNAL}"
elif [ "${OPTION}" == "${OPT_EXTERNAL}" ]
then
  show "${EXTERNAL}" && hide "${INTERNAL}"
elif [ "${OPTION}" == "${OPT_BOTH}" ]
then
  show "${EXTERNAL}"
  show "${INTERNAL}"
fi
```

* I wrote this script using the example from https://github.com/davatorium/rofi-scripts/blob/master/i3_switch_workspace.sh.
* It is relatively straight-forward to include other shortcuts to configure the display
* rofi has various themes, I included a screenshot of the default theme

**Comment by alex-courtis** [comment]
That is just fantastic! Thank you so much.

I've moved things to a wiki, with a [recipes](https://github.com/alex-courtis/way-displays/wiki/Recipes) page.

I'd be most grateful if you could add you recipe in there - you should get the credit ;)

**Comment by jeadorf** [comment]
Happy to make the edit myself.

**Comment by alex-courtis** [comment]
Added to the recipes.

**Comment by jeadorf** [comment]
Sorry for sitting on this so long ... https://github.com/alex-courtis/way-displays/wiki/Recipes looks good. Thank you!

**Comment by alex-courtis** [comment]
No worries; please do update it as needed.
