### ISSUE TITLE
Mouse can't move accross monitors on edges 

### ISSUE THREAD

**Issue by hyperion-ak** [alex-courtis/way-displays#146]
I have a laptop display and external monitor setup configured with ALIGN=MIDDLE. When moving the mouse from the external monitor over to the laptop display (smaller screen size), the cursor can not move across on the top and bottom part of the edge. However, the cursor can move in the middle.

I think this is related to the different size of the two monitors.

**Comment by alex-courtis** [comment]
Unfortunately way-displays cannot do anything about that, it simply tells the compositor what size and where the monitors are.

We'll need the compositor to do that "warping" of the mouse. Which compositor are you using? You could raise a feature request - it sounds like a great use case.

**Comment by hyperion-ak** [comment]
Hi, thank you for your reply. I am using way-displays with sway as a compositor.

**Comment by alex-courtis** [comment]
Very quick search shows https://github.com/swaywm/sway/issues/6607

If that's the one, give it a thumbs up to vote.

**Comment by alex-courtis** [comment]
This will identify if there are mismatches: #157

**Comment by alex-courtis** [comment]
This issue should be resolved via #138
Any 1-pixel-rounding-error gaps are now handled by the compositor and way-displays, using the new fractional scaling protocol agreements.

Please comment or reopen if you have any further issues.
