### ISSUE TITLE
enable bithdepth 10 on monitors

### ISSUE THREAD

**Issue by andresparrab** [alex-courtis/way-displays#176]
I cant find anywhere where i can set the bitdepth for monitors. 
Im using hyprland and in the hyprland config i have sett bitdepth10 , that is the only way that i can get screen share my monitor  working.

But i have now removed the monitor settings in hyprland and let way-display set up all my monitors on plug in. working great. but now i cant screen share. because it seems that hyprland need bitdepth to be set.

Or is there an already setting for this that i have missed?

**Comment by alex-courtis** [comment]
HDR (10 bit) is very experimental and not fully implemented: https://wiki.archlinux.org/title/HDR_monitor_support https://github.com/hyprwm/Hyprland/issues/4933

Unfortunately the wlroots protocols do not offer HDR and Hyprland doesn't offer a protocol to enable this.

Suggestion: set bitdepth10 via hyprland [config](https://wiki.hyprland.org/Configuring/Monitors/#10-bit-support) and have way-displays handle everything else.
Perhaps something like
```
monitor = eDP-1, , , , bitdepth, 10
```
An arrangement like this for VRR was successful for sway during the VRR implementation period.

**Comment by zeptic99** [comment]
> Unfortunately the wlroots protocols do not offer HDR and Hyprland doesn't offer a protocol to enable this.

Hyprland ditched wlroots a while back. Maybe HDR and 10-bit color support can be added into aquamarine?

**Comment by alex-courtis** [comment]
Did the suggestion above work correctly?

> > Unfortunately the wlroots protocols do not offer HDR and Hyprland doesn't offer a protocol to enable this.
> 
> Hyprland ditched wlroots a while back. Maybe HDR and 10-bit color support can be added into aquamarine?

Interesting... way-displays requires wlroots protocols. Perhaps they retained a subset.

HDR? I wish. It's a long way away. Only steamos (gamescope) has a full working implementation, however it uses a patched kernel.

**Comment by zeptic99** [comment]
> HDR? I wish. It's a long way away. Only steamos (gamescope) has a full working implementation, however it uses a patched kernel.

Not really. KDE has working HDR support.

**Comment by alex-courtis** [comment]
@andresparrab is there any action required here?

@zeptic99 is there anything specific I can help you with? Do you have a similar issue?

**Comment by littleblack111** [comment]
can we have HDR support? like how KDE implemented their own? can we do that with aquamarine

**Comment by alex-courtis** [comment]
> can we have HDR support? like how KDE implemented their own? can we do that with aquamarine

Added:
* #178

This will be built as soon as wlroots and compositors add the functionality.
