### ISSUE TITLE
Added package to nixpks

### ISSUE THREAD

**Issue by simoneruffini** [alex-courtis/way-displays#45]
Hi! as of [today](https://github.com/NixOS/nixpkgs/pull/177582) `way-displays` can be installed via `nix` package manager (Linux distros using `nix` and NixOS).
The package is available from the unstable  branch of `nixpks`. Probably will be merged in the next release as stable.

I am the current maintainer for that package, I will update it when new versions will be available. But if any of you wants to do it the necessary changes to update the package are realy simple.

For the future we can think to ad a CI/CD process so that the package can be directly downloaded from GitHub instead of building it on the host platform.

**Comment by alex-courtis** [comment]
That's fantastic, thanks @simoneruffini 

Everything looks smooth except for the [/etc patch](https://github.com/NixOS/nixpkgs/pull/177582/files#diff-a48b465e549bd3f8e82b3159c36eb8da9c58f9b84b11bda11f63e4b94471b61eR21)

Can we change the code so that you don't have to apply that patch? Is there perhaps an environment variable that we could use?

**Comment by alex-courtis** [comment]
> For the future we can think to ad a CI/CD process so that the package can be directly downloaded from GitHub instead of building it on the host platform.

That would be ideal. It only needs to be done for Linux as FreeBSD already have their own build process.

Time is limited...

**Comment by simoneruffini** [comment]
> Everything looks smooth except for the [/etc patch](https://github.com/NixOS/nixpkgs/pull/177582/files#diff-a48b465e549bd3f8e82b3159c36eb8da9c58f9b84b11bda11f63e4b94471b61eR21)

> Can we change the code so that you don't have to apply that patch? Is there perhaps an environment variable that we could use?

I will ask some NixOS gurus on how to do that, because I don't know if it is a good idea to have a env variable that let's you change the default position of the configuration files (the one you find in `../etc`). I will check how this is get accomplished.

**Comment by alex-courtis** [comment]
> I will check how this is get accomplished.

Perhaps a #define with an `/etc` default?

**Comment by simoneruffini** [comment]
So this means that a patch will be necessary anyway? Just in a more precise spot?

**Comment by alex-courtis** [comment]
I am aiming for no patches. Patches are fragile and need maintenance. We've removed all patches from the BSD and other distro's builds and I'd like to do the same here.

We could perhaps simply use `PREFIX_ETC` in the makeFlags as a #define and add another search in `cfg.cpp` e.g.

```c
	if (!found)
		found = resolve_paths(cfg, PREFIX_ETC"/etc", "");
```

However, other package builds may use DESTDIR and PREFIX* to target their staging area, so using those might not be a good idea.

Best solution would be a specific makeFlag -> #define for this case, maybe `FHS_ETC` or `ROOT_ETC`, defaulting to `/etc`.

**Comment by alex-courtis** [comment]
Merged. Do you need a release @simoneruffini ?

**Comment by simoneruffini** [comment]
I closed this issue because the package is available but maybe we can keep it open until I check the other one

**Comment by alex-courtis** [comment]
1.6.0 release PR for nixpkgs https://github.com/NixOS/nixpkgs/pull/182041
