### ISSUE TITLE
Feature: ORDER_LAST

### ISSUE THREAD

**Issue by alex-courtis** [alex-courtis/way-displays#46]
https://www.reddit.com/r/swaywm/comments/ruhc0t/best_way_to_have_monitor_of_unknown_size_above_a/hqzkeng/?utm_source=reddit&utm_medium=web2x&context=3

Order after all other monitors, allowing to be ordered after unknown.

**Comment by wdv4758h** [comment]
I just start trying way-displays. It works great and simple, thanks! And I'm thinking about exactly this feature. For now, I simply add `DP-1` `DP-2` `DP-3` ... and then `eDP-1` in the last. Which is good enough for my laptop and most of the scenario. But a way to define more generic order is a plus.

**Comment by alex-courtis** [comment]
Order last may be achieved via a [regex in ORDER](https://github.com/alex-courtis/way-displays/blob/master/doc/CONFIGURATION.md#order)

If the need arises, an explicit "middle marker" could be added: https://github.com/alex-courtis/way-displays/pull/68#issuecomment-1445561777
