### ISSUE TITLE
Doesn't work with sway 1.8-rc2

### ISSUE THREAD

**Issue by okhsunrog** [alex-courtis/way-displays#53]
using the latest way-display with sway 1.8-rc2, wlroots 0.16.0. arch linux.
user in added in input group.

way-display fails to start.
logs:

I [00:24:58] way-displays version 1.6.0
I [00:24:58] 
I [00:24:58] Found configuration file: /home/okhsunrog/.config/way-displays/cfg.yaml
I [00:24:58] 
I [00:24:58] Active configuration:
I [00:24:58]   Arrange in a ROW aligned at the TOP
I [00:24:58]   Order:
I [00:24:58]     eDP-1
I [00:24:58]     monitor description
I [00:24:58]     HDMI-A-1
I [00:24:58]   Auto scale: ON
I [00:24:58]   Laptop display prefix: eDP
I [00:24:58] 
I [00:24:58] Monitoring lid device: /dev/input/event1
I [00:24:58] 
I [00:24:58] Lid open
interface 'zwlr_output_head_v1' has no event 13
E [00:24:58] 
E [00:24:58] ERROR: wl_display_read_events failed at src/server.c:166, exiting: 2 No such file or directory
E [00:24:58] 
E [00:24:58] ERROR: Please raise an issue: https://github.com/alex-courtis/way-displays/issues
E [00:24:58] ERROR: Attach this log and describe the events that occurred before this failure.

**Comment by alex-courtis** [comment]
Thank you for raising this issue. Attempting replication.

**Comment by alex-courtis** [comment]
Fixed `zwlr_output_manager_v1_interface` to version 3.

Working: sway 1.8-rc2 wlroots 0.16.0

**Comment by okhsunrog** [comment]
@alex-courtis tested with the same setup, works fine. Thanks you!
