### ISSUE TITLE
Feature: CLI Flag Specifying Config File

### ISSUE THREAD

**Issue by p0da** [alex-courtis/way-displays#59]
Would you consider adding a flag that disables the config file searching behavior described [here](https://github.com/alex-courtis/way-displays/blob/master/doc/CONFIGURATION.md#file-locations) and  just reads the specified file?

And thanks for writing this, its certainly an improvement over the existing utilities in the space.

**Comment by alex-courtis** [comment]
That sounds fine. I can imagine some use cases.

[PRs](https://github.com/alex-courtis/way-displays/blob/master/CONTRIBUTING.md) are gratefully accepted.

**Comment by alex-courtis** [comment]
Added option:
```
  -c, --c[onfig]        <path>
```

I would be most grateful if you could test this prior to release:
```sh
git clone git@github.com:alex-courtis/way-displays.git
cd way-displays
make
./way-displays --help
./way-displays --config /path/to/my/config.yaml
```

**Comment by p0da** [comment]
Works perfectly, thanks for taking the time. 

As a side note, it seems like VRR is now added and always on for river? Would it be possible to add some per monitor toggle for it? I can open a new issue if that works better.

**Comment by alex-courtis** [comment]
Thanks for testing.

> As a side note, it seems like VRR is now added and always on for river? Would it be possible to add some per monitor toggle for it? I can open a new issue if that works better.

Please do. I applied YAGNI when adding VRR, however now we do need it.
