### ISSUE TITLE
Feature: Per Monitor VRR Toggle

### ISSUE THREAD

**Issue by p0da** [alex-courtis/way-displays#70]
As per https://github.com/alex-courtis/way-displays/issues/59#issuecomment-1453204405, a per monitor VRR toggle would be quite useful.

**Comment by alex-courtis** [comment]
VRR enabled is the desirable (current) default.

It could be disabled as per `DISABLED` e.g.
```yaml
VRR_OFF:
  - "eDP-1"
  - !.*Gigabyte.*
```

@p0da what is the use case for disabling VRR? I think I might be missing something that should be captured/configured.

**Comment by alex-courtis** [comment]
@p0da `VRR_OFF` has been added. I would be most grateful if you could test on master this prior to release:

```sh
git clone git@github.com:alex-courtis/way-displays.git
cd way-displays
make
sudo make install
```

See https://github.com/alex-courtis/way-displays/blob/master/doc/CONFIGURATION.md#vrr_off

**Comment by alex-courtis** [comment]
> Thanks for adding the option, worked well for me during testing.

Many thanks.
