### ISSUE TITLE
1.9.0 Roadmap

### ISSUE THREAD

**Issue by alex-courtis** [alex-courtis/way-displays#85]
- [ ] #78
- [ ] #40
- [ ] #65
- [ ] #83 
- [ ] #81
- [ ] #43

**Comment by xeruf** [comment]
I would recommend to use Milestones to track such lists properly ;)
Can we set a little bounty or otherwise help you prioritize working on this? Would be awesome to have these options!

**Comment by alex-courtis** [comment]
That's a great idea! Today I Learned about that feature.

**Comment by alex-courtis** [comment]
[1.9](https://github.com/alex-courtis/way-displays/milestone/1)

Issues are roughly prioritised... Transformation is really close.

Not sure about bounties; my eternal gratitude is always there.
